Chat/Storage DB schema
maximVorochaev/filethread-demo pull request #9
Opened 2020-11-26 12:12 UTC by maximVorochaev

Added:  
   - liquibase scripts
   - changeset tags
   - tables for chat/storage schema
   - liquibase mvn plugin
   - liquibase properties

Changed:
   - model classes

2020-11-26 12:17 UTC, PavelEvdokimovich approved these changes

2020-11-27 11:03 UTC, IharYudziankou requested changes

2020-11-27 11:03 UTC, IharYudziankou commented on filethread-db/src/main/resources/db/changelog/db.changelog-1.1.xml
> +            <column name="message_status" type="VARCHAR(30)">
What is purpose of this field? Should it be ENUM ?

2020-11-27 11:03 UTC, IharYudziankou commented on notification/src/main/java/com/itechart/filethread/notification/dto/mapper/ChatMessageMapper.java
> +    @Mapping(source = "senderName", target = "person.firstName")
Do we really need sender name? if so first name and last name is required

2020-11-27 12:10 UTC, merged